import sys
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]

if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

from src.data.preprocess import SENSOR_COLUMNS, SETTING_COLUMNS
from src.models.predict import load_artifacts, predict_raw_dataframe


MODEL_DIR = ROOT / "models"
DASHBOARD_CSV = ROOT / "data" / "processed" / "test_dashboard.csv"

st.set_page_config(
    page_title="Predictive Maintenance Dashboard",
    layout="wide"
)


@st.cache_resource
def get_artifacts():
    """
    Load model artifacts.
    """
    return load_artifacts(MODEL_DIR)


@st.cache_data(ttl=3600)
def get_sample_data():
    """
    Load sample dashboard dataset generated by train.py.
    """
    if DASHBOARD_CSV.exists():
        return pd.read_csv(DASHBOARD_CSV)
    return None


def status_from_rul(rul, warning_threshold, critical_threshold):
    """
    Convert predicted RUL into maintenance status.
    """
    if pd.isna(rul):
        return "Unknown"

    if rul <= critical_threshold:
        return "Critical"

    if rul <= warning_threshold:
        return "Warning"

    return "Healthy"


def last_cycle_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Get latest row per engine.
    """
    df = df.sort_values(["engine_no", "cycle"])
    return df.groupby("engine_no").tail(1).reset_index(drop=True)


def fleet_view(df: pd.DataFrame, warning_threshold: int, critical_threshold: int):
    """
    Show fleet-level summary.
    """
    st.subheader("Fleet Health")

    last = last_cycle_df(df).copy()

    last["status"] = last["predicted_rul"].apply(
        lambda x: status_from_rul(
            x,
            warning_threshold,
            critical_threshold
        )
    )

    if "rul" in last.columns:
        last["absolute_error"] = (
            last["predicted_rul"] - last["rul"]
        ).abs().round(2)

    last = last.sort_values("predicted_rul")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric("Engines", len(last))
    c2.metric(
        "Average predicted RUL",
        round(last["predicted_rul"].mean(), 2)
    )
    c3.metric(
        "Critical engines",
        int((last["status"] == "Critical").sum())
    )
    c4.metric(
        "Warning engines",
        int((last["status"] == "Warning").sum())
    )

    st.markdown("### Status distribution")

    status_order = ["Critical", "Warning", "Healthy", "Unknown"]

    status_counts = (
        last["status"]
        .value_counts()
        .reindex(status_order, fill_value=0)
    )

    st.bar_chart(status_counts)

    st.markdown("### Highest-risk engines")

    show_cols = [
        col for col in [
            "engine_no",
            "cycle",
            "predicted_rul",
            "rul",
            "absolute_error",
            "status"
        ]
        if col in last.columns
    ]

    st.dataframe(
        last[show_cols].head(25),
        use_container_width=True
    )


def engine_view(df: pd.DataFrame):
    """
    Show detailed view for one engine.
    """
    st.subheader("Engine Detail")

    available_sensors = [
        col for col in SENSOR_COLUMNS if col in df.columns
    ]

    engines = sorted(df["engine_no"].unique())

    engine = st.selectbox(
        "Select engine",
        engines
    )

    engine_df = (
        df[df["engine_no"] == engine]
        .sort_values("cycle")
    )

    left, right = st.columns([2, 1])

    with right:
        if "predicted_rul" in engine_df.columns:
            st.metric(
                "Latest predicted RUL",
                round(engine_df["predicted_rul"].iloc[-1], 2)
            )

        if "rul" in engine_df.columns:
            st.metric(
                "Latest true RUL",
                round(engine_df["rul"].iloc[-1], 2)
            )

        if "cycle" in engine_df.columns:
            st.metric(
                "Latest cycle",
                int(engine_df["cycle"].iloc[-1])
            )

    selected_sensors = st.multiselect(
        "Sensor channels",
        available_sensors,
        default=available_sensors[:6]
    )

    if selected_sensors:
        st.markdown("### Sensor trends")
        st.line_chart(engine_df.set_index("cycle")[selected_sensors])

    if "predicted_rul" in engine_df.columns:
        st.markdown("### Predicted RUL over time")
        st.line_chart(engine_df.set_index("cycle")[["predicted_rul"]])


def model_performance_view(metadata: dict):
    """
    Show model performance metrics and feature importances.
    """
    st.subheader("Model Performance")

    metrics = metadata.get("metrics", {})

    validation = metrics.get("validation", {})
    test = metrics.get("test", {})

    if validation:
        st.markdown("**Validation: last cycle of held-out engines**")

        c1, c2, c3, c4 = st.columns(4)

        c1.metric("MAE", round(validation.get("mae", 0), 2))
        c2.metric("RMSE", round(validation.get("rmse", 0), 2))
        c3.metric("R²", round(validation.get("r2", 0), 2))
        c4.metric(
            "Within 10 cycles",
            f"{round(validation.get('within_10_cycles', 0) * 100, 1)}%"
        )

    if test:
        st.markdown("**Test: last cycle of test fleet**")

        c1, c2, c3, c4 = st.columns(4)

        c1.metric("MAE", round(test.get("mae", 0), 2))
        c2.metric("RMSE", round(test.get("rmse", 0), 2))
        c3.metric("R²", round(test.get("r2", 0), 2))
        c4.metric(
            "Within 10 cycles",
            f"{round(test.get('within_10_cycles', 0) * 100, 1)}%"
        )

    top_features = pd.DataFrame(metadata.get("top_features", []))

    if not top_features.empty:
        st.markdown("### Top feature importances")
        st.bar_chart(top_features.set_index("feature")["importance"])


def process_upload(uploaded_file, model, feature_columns, metadata):
    """
    Process uploaded raw CSV file.
    """
    raw = pd.read_csv(uploaded_file)

    required_columns = (
        ["engine_no", "cycle"]
        + SETTING_COLUMNS
        + SENSOR_COLUMNS
    )

    missing_columns = [
        col for col in required_columns if col not in raw.columns
    ]

    if missing_columns:
        st.error(
            f"Uploaded CSV is missing required columns: {missing_columns}"
        )
        return None

    predicted_df = predict_raw_dataframe(
        raw_df=raw,
        model=model,
        feature_columns=feature_columns,
        metadata=metadata
    )

    if predicted_df.empty:
        st.warning("No valid rows found after cleaning uploaded file.")

    return predicted_df


def main():
    st.title("Predictive Maintenance Dashboard")
    st.caption(
        "Predict remaining useful life (RUL) for machines using sensor telemetry."
    )

    if not (MODEL_DIR / "model.joblib").exists():
        st.error(
            "No trained model found. Run `python train.py` from the project root first."
        )
        st.stop()

    model, feature_columns, metadata = get_artifacts()

    st.sidebar.header("Dashboard settings")

    critical_threshold = st.sidebar.slider(
        "Critical threshold (cycles remaining)",
        min_value=1,
        max_value=60,
        value=10
    )

    warning_threshold = st.sidebar.slider(
        "Warning threshold (cycles remaining)",
        min_value=critical_threshold + 1,
        max_value=180,
        value=max(30, critical_threshold + 1)
    )

    source = st.sidebar.radio(
        "Data source",
        ["Sample fleet dataset", "Upload raw CSV"]
    )

    df = None

    if source == "Sample fleet dataset":
        df = get_sample_data()

        if df is None:
            st.info(
                "Sample dataset not found. Run `python train.py` to generate it, "
                "or upload a raw CSV file."
            )

    else:
        uploaded = st.sidebar.file_uploader(
            "Raw sensor CSV",
            type=["csv"]
        )

        template = pd.DataFrame(
            columns=["engine_no", "cycle"] + SETTING_COLUMNS + SENSOR_COLUMNS
        )

        st.sidebar.download_button(
            "Download CSV template",
            template.to_csv(index=False).encode(),
            file_name="raw_sensor_template.csv",
            mime="text/csv"
        )

        if uploaded is not None:
            df = process_upload(
                uploaded_file=uploaded,
                model=model,
                feature_columns=feature_columns,
                metadata=metadata
            )

    if df is None or df.empty:
        st.info("Waiting for data...")
        return

    if "predicted_rul" not in df.columns:
        st.error(
            "The current dataframe does not have `predicted_rul`. "
            "Re-run training or upload raw data."
        )
        return

    tabs = st.tabs([
        "Fleet",
        "Engine detail",
        "Model performance",
        "Data preview"
    ])

    with tabs[0]:
        fleet_view(df, warning_threshold, critical_threshold)

    with tabs[1]:
        engine_view(df)

    with tabs[2]:
        model_performance_view(metadata)

    with tabs[3]:
        st.dataframe(df.head(200), use_container_width=True)


if __name__ == "__main__":
    main() 
